# K-NN 分类器配置
data:
  data_dir: "../data"
  cv_sample_size: 10000
  test_subset_size: 10000

model:
  k_values: [1, 3, 5, 7, 9, 11]
  n_folds: 3
  batch_size: 1000

training:
  random_seed: 42

results:
  save_dir: "../results"
  plots_dir: "../results/plots"
